In [71]:
import pandas as pd
import os
import numpy as np

In [72]:
df1 = pd.read_csv('GSE162164_RAW/GSM4943767_TB_HIV_1.txt.gz', sep="\t" )
df1

            TB_HIV_1
ARF5             143
M6PR             171
ESRRA             44
FKBP4             55
CYP26B1            0
...              ...
LINC01862          0
ARHGAP35         169
GNL3L              2
SLFN14            20
SNORA74C-2         1

[14440 rows x 1 columns]

In [73]:
df2 = pd.read_csv('GSE162164_RAW/GSM4943768_TB_HIV_2.txt.gz', sep="\t")
df2

            TB_HIV_2
ARF5             215
M6PR             245
ESRRA            118
FKBP4             58
CYP26B1            0
...              ...
LINC01862          1
ARHGAP35         143
GNL3L              5
SLFN14            24
SNORA74C-2         1

[14440 rows x 1 columns]

In [74]:
# 将文件名以列表的形式存放，方便后续读取文件
files = []
for file in os.listdir('GSE162164_RAW'):
    if(file.endswith('.txt.gz')):
        files.append(file)
print(files)
pd.array(files)

['GSM4943770_HIV_4.txt.gz', 'GSM4943784_HIV_18.txt.gz', 'GSM4943780_HIV_14.txt.gz', 'GSM4943789_TB_HIV_23.txt.gz', 'GSM4943767_TB_HIV_1.txt.gz', 'GSM4943787_TB_HIV_21.txt.gz', 'GSM4943769_TB_HIV_3.txt.gz', 'GSM4943773_HIV_7.txt.gz', 'GSM4943771_TB_HIV_5.txt.gz', 'GSM4943772_TB_HIV_6.txt.gz', 'GSM4943785_HIV_19.txt.gz', 'GSM4943790_TB_HIV_24.txt.gz', 'GSM4943783_HIV_17.txt.gz', 'GSM4943786_TB_HIV_20.txt.gz', 'GSM4943791_TB_HIV_25.txt.gz', 'GSM4943768_TB_HIV_2.txt.gz', 'GSM4943776_HIV_10.txt.gz', 'GSM4943788_TB_HIV_22.txt.gz', 'GSM4943774_HIV_8.txt.gz', 'GSM4943779_TB_HIV_13.txt.gz', 'GSM4943781_TB_HIV_15.txt.gz', 'GSM4943777_HIV_11.txt.gz', 'GSM4943782_HIV_16.txt.gz', 'GSM4943778_HIV_12.txt.gz', 'GSM4943775_TB_HIV_9.txt.gz']

<StringArray>
[    'GSM4943770_HIV_4.txt.gz',    'GSM4943784_HIV_18.txt.gz',
    'GSM4943780_HIV_14.txt.gz', 'GSM4943789_TB_HIV_23.txt.gz',
  'GSM4943767_TB_HIV_1.txt.gz', 'GSM4943787_TB_HIV_21.txt.gz',
  'GSM4943769_TB_HIV_3.txt.gz',     'GSM4943773_HIV_7.txt.gz',
  'GSM4943771_TB_HIV_5.txt.gz',  'GSM4943772_TB_HIV_6.txt.gz',
    'GSM4943785_HIV_19.txt.gz', 'GSM4943790_TB_HIV_24.txt.gz',
    'GSM4943783_HIV_17.txt.gz', 'GSM4943786_TB_HIV_20.txt.gz',
 'GSM4943791_TB_HIV_25.txt.gz',  'GSM4943768_TB_HIV_2.txt.gz',
    'GSM4943776_HIV_10.txt.gz', 'GSM4943788_TB_HIV_22.txt.gz',
     'GSM4943774_HIV_8.txt.gz', 'GSM4943779_TB_HIV_13.txt.gz',
 'GSM4943781_TB_HIV_15.txt.gz',    'GSM4943777_HIV_11.txt.gz',
    'GSM4943782_HIV_16.txt.gz',    'GSM4943778_HIV_12.txt.gz',
  'GSM4943775_TB_HIV_9.txt.gz']
Length: 25, dtype: string

In [75]:
dfs = []
for file in files:
    # 转置：给的数据样本：特征在行，标签在列。
    df = (pd.read_csv("GSE162164_RAW/"+ file, sep = '\t')).T
    # 乘1.0是为了转化成浮点型数据
    dfs.append(df*1.0)
# 合并
dfs_con = pd.concat(dfs)
dfs_con

,ARF5,M6PR,ESRRA,FKBP4,CYP26B1,NDUFAF7,FUCA2,HS3ST1,CYP51A1,USP28,...,TSPYL1,GPRASP1,LINC01949,MIR1915HG,PARTICL,LINC01862,ARHGAP35,GNL3L,SLFN14,SNORA74C-2
HIV_4,171.0,247.0,75.0,36.0,0.0,32.0,36.0,4.0,35.0,10.0,...,212.0,48.0,206.0,3.0,12.0,0.0,218.0,8.0,37.0,1.0
HIV_18,216.0,285.0,66.0,61.0,0.0,58.0,52.0,1.0,44.0,0.0,...,297.0,43.0,224.0,6.0,6.0,7.0,141.0,5.0,60.0,1.0
HIV_14,114.0,250.0,76.0,24.0,0.0,41.0,33.0,0.0,89.0,53.0,...,229.0,39.0,182.0,2.0,9.0,0.0,221.0,0.0,11.0,4.0
TB_HIV_23,258.0,180.0,70.0,155.0,0.0,51.0,35.0,0.0,41.0,8.0,...,147.0,26.0,226.0,4.0,4.0,0.0,158.0,0.0,15.0,2.0
TB_HIV_1,143.0,171.0,44.0,55.0,0.0,38.0,35.0,2.0,32.0,24.0,...,130.0,32.0,296.0,2.0,6.0,0.0,169.0,2.0,20.0,1.0
TB_HIV_21,185.0,187.0,85.0,69.0,0.0,30.0,29.0,0.0,59.0,0.0,...,113.0,10.0,196.0,3.0,5.0,0.0,66.0,1.0,19.0,1.0
TB_HIV_3,123.0,89.0,43.0,50.0,1.0,21.0,18.0,0.0,17.0,0.0,...,77.0,20.0,190.0,2.0,5.0,1.0,87.0,2.0,41.0,2.0
HIV_7,141.0,198.0,36.0,96.0,0.0,44.0,32.0,0.0,46.0,0.0,...,127.0,16.0,175.0,2.0,5.0,8.0,120.0,0.0,35.0,0.0
TB_HIV_5,133.0,75.0,47.0,10.0,0.0,17.0,17.0,0.0,14.0,16.0,...,86.0,35.0,156.0,4.0,2.0,2.0,135.0,0.0,53.0,0.0
TB_HIV_6,121.0,231.0,72.0,42.0,0.0,47.0,73.0,2.0,45.0,0.0,...,178.0,32.0,272.0,5.0,8.0,3.0,227.0,0.0,7.0,0.0
HIV_19,226.0,291.0,73.0,59.0,0.0,49.0,51.0,2.0,42.0,0.0,...,237.0,27.0,253.0,4.0,7.0,0.0,130.0,3.0,35.0,0.0
TB_HIV_24,122.0,218.0,32.0,29.0,0.0,16.0,39.0,0.0,49.0,15.0,...,167.0,21.0,235.0,10.0,8.0,0.0,96.0,3.0,63.0,1.0
HIV_17,338.0,297.0,134.0,44.0,6.0,51.0,55.0,4.0,64.0,42.0,...,251.0,64.0,293.0,3.0,19.0,1.0,204.0,0.0,19.0,0.0
TB_HIV_20,155.0,116.0,79.0,113.0,0.0,38.0,21.0,1.0,24.0,0.0,...,170.0,7.0,169.0,5.0,8.0,2.0,107.0,0.0,27.0,1.0
TB_HIV_25,128.0,245.0,84.0,117.0,1.0,40.0,53.0,8.0,110.0,0.0,...,247.0,35.0,289.0,4.0,8.0,1.0,244.0,0.0,12.0,4.0
TB_HIV_2,215.0,245.0,118.0,58.0,0.0,30.0,30.0,1.0,70.0,0.0,...,240.0,25.0,227.0,4.0,7.0,1.0,143.0,5.0,24.0,1.0
HIV_10,160.0,215.0,90.0,55.0,0.0,16.0,33.0,3.0,61.0,0.0,...,219.0,49.0,207.0,5.0,5.0,2.0,238.0,0.0,13.0,1.0
TB_HIV_22,112.0,111.0,27.0,73.0,0.0,29.0,18.0,0.0,29.0,32.0,...,85.0,16.0,240.0,3.0,7.0,0.0,88.0,7.0,27.0,0.0
HIV_8,125.0,189.0,75.0,32.0,2.0,20.0,36.0,0.0,23.0,47.0,...,160.0,32.0,204.0,3.0,14.0,3.0,163.0,0.0,16.0,0.0
TB_HIV_13,198.0,121.0,50.0,39.0,0.0,70.0,24.0,2.0,48.0,0.0,...,78.0,8.0,265.0,6.0,5.0,0.0,137.0,0.0,33.0,2.0
TB_HIV_15,140.0,194.0,27.0,76.0,0.0,37.0,26.0,1.0,54.0,0.0,...,234.0,27.0,177.0,2.0,9.0,2.0,85.0,0.0,69.0,1.0
HIV_11,158.0,270.0,92.0,37.0,0.0,59.0,42.0,5.0,57.0,77.0,...,162.0,43.0,242.0,1.0,17.0,5.0,157.0,0.0,37.0,3.0
HIV_16,179.0,347.0,105.0,70.0,0.0,68.0,47.0,6.0,66.0,17.0,...,377.0,45.0,234.0,6.0,11.0,2.0,223.0,0.0,85.0,1.0
HIV_12,145.0,241.0,74.0,73.0,0.0,39.0,26.0,6.0,75.0,54.0,...,241.0,27.0,252.0,1.0,10.0,4.0,202.0,0.0,41.0,3.0
TB_HIV_9,138.0,199.0,89.0,47.0,13.0,41.0,30.0,1.0,52.0,0.0,...,195.0,47.0,241.0,3.0,16.0,3.0,204.0,4.0,8.0,2.0

In [76]:
marks = []
for sample in dfs_con.index:
    if sample.startswith("TB"):
        marks.append('TB+HIV')
    else:
        marks.append('HIV')
print(marks)

['HIV', 'HIV', 'HIV', 'TB+HIV', 'TB+HIV', 'TB+HIV', 'TB+HIV', 'HIV', 'TB+HIV', 'TB+HIV', 'HIV', 'TB+HIV', 'HIV', 'TB+HIV', 'TB+HIV', 'TB+HIV', 'HIV', 'TB+HIV', 'HIV', 'TB+HIV', 'TB+HIV', 'HIV', 'HIV', 'HIV', 'TB+HIV']

In [77]:
print(marks.count("TB+HIV"))
print(marks.count("HIV"))

14
11

In [78]:
TB = []
HIV = []
for sample in dfs_con.index:
    if sample.startswith("TB"):
        TB.append(sample)
    else:
        HIV.append(sample)

In [79]:
TB

['TB_HIV_23',
 'TB_HIV_1',
 'TB_HIV_21',
 'TB_HIV_3',
 'TB_HIV_5',
 'TB_HIV_6',
 'TB_HIV_24',
 'TB_HIV_20',
 'TB_HIV_25',
 'TB_HIV_2',
 'TB_HIV_22',
 'TB_HIV_13',
 'TB_HIV_15',
 'TB_HIV_9']

In [80]:
HIV

['HIV_4',
 'HIV_18',
 'HIV_14',
 'HIV_7',
 'HIV_19',
 'HIV_17',
 'HIV_10',
 'HIV_8',
 'HIV_11',
 'HIV_16',
 'HIV_12']

In [81]:
df_TB = dfs_con.loc[TB]
df_HIV = dfs_con.loc[HIV]

In [82]:
df_TB

,ARF5,M6PR,ESRRA,FKBP4,CYP26B1,NDUFAF7,FUCA2,HS3ST1,CYP51A1,USP28,...,TSPYL1,GPRASP1,LINC01949,MIR1915HG,PARTICL,LINC01862,ARHGAP35,GNL3L,SLFN14,SNORA74C-2
TB_HIV_23,258.0,180.0,70.0,155.0,0.0,51.0,35.0,0.0,41.0,8.0,...,147.0,26.0,226.0,4.0,4.0,0.0,158.0,0.0,15.0,2.0
TB_HIV_1,143.0,171.0,44.0,55.0,0.0,38.0,35.0,2.0,32.0,24.0,...,130.0,32.0,296.0,2.0,6.0,0.0,169.0,2.0,20.0,1.0
TB_HIV_21,185.0,187.0,85.0,69.0,0.0,30.0,29.0,0.0,59.0,0.0,...,113.0,10.0,196.0,3.0,5.0,0.0,66.0,1.0,19.0,1.0
TB_HIV_3,123.0,89.0,43.0,50.0,1.0,21.0,18.0,0.0,17.0,0.0,...,77.0,20.0,190.0,2.0,5.0,1.0,87.0,2.0,41.0,2.0
TB_HIV_5,133.0,75.0,47.0,10.0,0.0,17.0,17.0,0.0,14.0,16.0,...,86.0,35.0,156.0,4.0,2.0,2.0,135.0,0.0,53.0,0.0
TB_HIV_6,121.0,231.0,72.0,42.0,0.0,47.0,73.0,2.0,45.0,0.0,...,178.0,32.0,272.0,5.0,8.0,3.0,227.0,0.0,7.0,0.0
TB_HIV_24,122.0,218.0,32.0,29.0,0.0,16.0,39.0,0.0,49.0,15.0,...,167.0,21.0,235.0,10.0,8.0,0.0,96.0,3.0,63.0,1.0
TB_HIV_20,155.0,116.0,79.0,113.0,0.0,38.0,21.0,1.0,24.0,0.0,...,170.0,7.0,169.0,5.0,8.0,2.0,107.0,0.0,27.0,1.0
TB_HIV_25,128.0,245.0,84.0,117.0,1.0,40.0,53.0,8.0,110.0,0.0,...,247.0,35.0,289.0,4.0,8.0,1.0,244.0,0.0,12.0,4.0
TB_HIV_2,215.0,245.0,118.0,58.0,0.0,30.0,30.0,1.0,70.0,0.0,...,240.0,25.0,227.0,4.0,7.0,1.0,143.0,5.0,24.0,1.0
TB_HIV_22,112.0,111.0,27.0,73.0,0.0,29.0,18.0,0.0,29.0,32.0,...,85.0,16.0,240.0,3.0,7.0,0.0,88.0,7.0,27.0,0.0
TB_HIV_13,198.0,121.0,50.0,39.0,0.0,70.0,24.0,2.0,48.0,0.0,...,78.0,8.0,265.0,6.0,5.0,0.0,137.0,0.0,33.0,2.0
TB_HIV_15,140.0,194.0,27.0,76.0,0.0,37.0,26.0,1.0,54.0,0.0,...,234.0,27.0,177.0,2.0,9.0,2.0,85.0,0.0,69.0,1.0
TB_HIV_9,138.0,199.0,89.0,47.0,13.0,41.0,30.0,1.0,52.0,0.0,...,195.0,47.0,241.0,3.0,16.0,3.0,204.0,4.0,8.0,2.0

In [83]:
df_HIV

,ARF5,M6PR,ESRRA,FKBP4,CYP26B1,NDUFAF7,FUCA2,HS3ST1,CYP51A1,USP28,...,TSPYL1,GPRASP1,LINC01949,MIR1915HG,PARTICL,LINC01862,ARHGAP35,GNL3L,SLFN14,SNORA74C-2
HIV_4,171.0,247.0,75.0,36.0,0.0,32.0,36.0,4.0,35.0,10.0,...,212.0,48.0,206.0,3.0,12.0,0.0,218.0,8.0,37.0,1.0
HIV_18,216.0,285.0,66.0,61.0,0.0,58.0,52.0,1.0,44.0,0.0,...,297.0,43.0,224.0,6.0,6.0,7.0,141.0,5.0,60.0,1.0
HIV_14,114.0,250.0,76.0,24.0,0.0,41.0,33.0,0.0,89.0,53.0,...,229.0,39.0,182.0,2.0,9.0,0.0,221.0,0.0,11.0,4.0
HIV_7,141.0,198.0,36.0,96.0,0.0,44.0,32.0,0.0,46.0,0.0,...,127.0,16.0,175.0,2.0,5.0,8.0,120.0,0.0,35.0,0.0
HIV_19,226.0,291.0,73.0,59.0,0.0,49.0,51.0,2.0,42.0,0.0,...,237.0,27.0,253.0,4.0,7.0,0.0,130.0,3.0,35.0,0.0
HIV_17,338.0,297.0,134.0,44.0,6.0,51.0,55.0,4.0,64.0,42.0,...,251.0,64.0,293.0,3.0,19.0,1.0,204.0,0.0,19.0,0.0
HIV_10,160.0,215.0,90.0,55.0,0.0,16.0,33.0,3.0,61.0,0.0,...,219.0,49.0,207.0,5.0,5.0,2.0,238.0,0.0,13.0,1.0
HIV_8,125.0,189.0,75.0,32.0,2.0,20.0,36.0,0.0,23.0,47.0,...,160.0,32.0,204.0,3.0,14.0,3.0,163.0,0.0,16.0,0.0
HIV_11,158.0,270.0,92.0,37.0,0.0,59.0,42.0,5.0,57.0,77.0,...,162.0,43.0,242.0,1.0,17.0,5.0,157.0,0.0,37.0,3.0
HIV_16,179.0,347.0,105.0,70.0,0.0,68.0,47.0,6.0,66.0,17.0,...,377.0,45.0,234.0,6.0,11.0,2.0,223.0,0.0,85.0,1.0
HIV_12,145.0,241.0,74.0,73.0,0.0,39.0,26.0,6.0,75.0,54.0,...,241.0,27.0,252.0,1.0,10.0,4.0,202.0,0.0,41.0,3.0

In [84]:
# 比较两组中每个特征的均值
mean_TB = df_TB.mean()
mean_HIV = df_HIV.mean()

In [85]:
mean_TB

ARF5          155.071429
M6PR          170.142857
ESRRA          61.928571
FKBP4          66.642857
CYP26B1         1.071429
                 ...
LINC01862       1.071429
ARHGAP35      139.000000
GNL3L           1.714286
SLFN14         29.857143
SNORA74C-2      1.285714
Length: 14440, dtype: float64

In [86]:
mean_HIV

ARF5          179.363636
M6PR          257.272727
ESRRA          81.454545
FKBP4          53.363636
CYP26B1         0.727273
                 ...
LINC01862       2.909091
ARHGAP35      183.363636
GNL3L           1.454545
SLFN14         35.363636
SNORA74C-2      1.272727
Length: 14440, dtype: float64

In [87]:
# 均值进行差值比较，从大到小排列
mean_abs = np.abs(mean_TB-mean_HIV)
print(mean_abs.sort_values(ascending = False).head(100))
# 通过结果可以看出，仅比较均值远远不够

HBA2         98754.987013
RN7SL1       62068.435065
RN7SL2       37517.584416
S100A9       18068.759740
MALAT1        6846.084416
                 ...
LINC00861      514.298701
NCF1           510.896104
TLR8           506.266234
ADIPOR1        505.188312
RPS4X          496.980519
Length: 100, dtype: float64

In [88]:
X = dfs_con.iloc[:, 0:]
zero_count = (X == 0).sum(axis=0)
zero_count

ARF5           0
M6PR           0
ESRRA          0
FKBP4          0
CYP26B1       20
              ..
LINC01862      9
ARHGAP35       0
GNL3L         15
SLFN14         0
SNORA74C-2     7
Length: 14440, dtype: int64

In [89]:
zero_count.describe()

count    14440.000000
mean         5.976801
std          7.365175
min          0.000000
25%          0.000000
50%          2.000000
75%         12.000000
max         24.000000
dtype: float64