In [42]:
import pandas as pd

In [43]:
df = pd.read_csv('Titanic.csv',index_col = 0)
df

    性别    年龄 船舱等级       费用  是否生还
0    男  22.0   三等   7.2500     0
1    女  38.0   一等  71.2833     1
2    女  26.0   三等   7.9250     1
3    女  35.0   一等  53.1000     1
4    男  35.0   三等   8.0500     0
..  ..   ...  ...      ...   ...
886  男  27.0   二等  13.0000     0
887  女  19.0   一等  30.0000     1
888  女   NaN   三等  23.4500     0
889  男  26.0   一等  30.0000     1
890  男  32.0   三等   7.7500     0

[891 rows x 5 columns]

In [44]:
# index，columns 决定“怎么分组”，values 决定“算什么”，aggfunc 决定“怎么算”
df1 = df.pivot_table(values = '是否生还',index = '性别',columns = '船舱等级',aggfunc = 'mean') # 默认聚合函数aggfunc = 'mean' 也可以改成自己写的函数
df1

船舱等级        一等        三等        二等
性别
女     0.968085  0.500000  0.921053
男     0.368852  0.135447  0.157407

In [45]:
df2 = df.pivot_table(values = '是否生还',index = '性别',aggfunc = 'mean')
df2

        是否生还
性别
女   0.742038
男   0.188908

In [46]:
# 多组数据透视
# 有的特征有很多数据，很难归类，需要使用cut/qcut 将这些数据离散化，也就是重新分组
# cut手动设置切分范围；qcut只需告诉它分组数量，自动切分

# 重置年龄列
age = pd.cut(df['年龄'],[-1,25,120])
age

0       (-1.0, 25.0]
1      (25.0, 120.0]
2      (25.0, 120.0]
3      (25.0, 120.0]
4      (25.0, 120.0]
           ...
886    (25.0, 120.0]
887     (-1.0, 25.0]
888              NaN
889    (25.0, 120.0]
890    (25.0, 120.0]
Name: 年龄, Length: 891, dtype: category
Categories (2, interval[int64, right]): [(-1, 25] < (25, 120]]

In [47]:
# 重置费用列
fare = pd.qcut(df['费用'],q = 2)
fare

0       (-0.001, 14.454]
1      (14.454, 512.329]
2       (-0.001, 14.454]
3      (14.454, 512.329]
4       (-0.001, 14.454]
             ...
886     (-0.001, 14.454]
887    (14.454, 512.329]
888    (14.454, 512.329]
889    (14.454, 512.329]
890     (-0.001, 14.454]
Name: 费用, Length: 891, dtype: category
Categories (2, interval[float64, right]): [(-0.001, 14.454] < (14.454, 512.329]]

In [49]:
df3 = df.pivot_table(values = '是否生还',index = [age,'性别'],columns = ['船舱等级',fare],aggfunc = 'mean')
df3

/var/folders/pf/dmmvsls119z2s_t0gq7gm7780000gn/T/ipykernel_98399/762161960.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df3 = df.pivot_table(values = '是否生还',index = [age,'性别'],columns = ['船舱等级',fare],aggfunc = 'mean')

船舱等级                       一等                                 三等  \
费用           (-0.001, 14.454] (14.454, 512.329] (-0.001, 14.454]
年龄        性别
(-1, 25]  女               NaN          0.928571         0.589744
          男               NaN          0.500000         0.147368
(25, 120] 女               NaN          0.982456         0.444444
          男               0.0          0.397590         0.134615

船舱等级                                         二等
费用           (14.454, 512.329] (-0.001, 14.454] (14.454, 512.329]
年龄        性别
(-1, 25]  女           0.384615         0.857143          1.000000
          男           0.176471         0.055556          0.500000
(25, 120] 女           0.315789         0.904762          0.875000
          男           0.200000         0.108108          0.038462