In [19]:
import pandas as pd

In [20]:
# 导入数据
df1 = pd.read_csv('Planetary_Data.csv',index_col = 0).head() # head()可以选择输入前x行，默认是前5行
print(df1)
df1

   发现时间  发现数量   观测方法    行星质量   距地距离     轨道周期
0  1989     1   径向速度  11.680  40.57  83.8880
1  1992     3  脉冲星计时     NaN    NaN  25.2620
2  1992     3  脉冲星计时     NaN    NaN  66.5419
3  1994     3  脉冲星计时     NaN    NaN  98.2114
4  1995     1   径向速度   0.472  15.36   4.2308

   发现时间  发现数量   观测方法    行星质量   距地距离     轨道周期
0  1989     1   径向速度  11.680  40.57  83.8880
1  1992     3  脉冲星计时     NaN    NaN  25.2620
2  1992     3  脉冲星计时     NaN    NaN  66.5419
3  1994     3  脉冲星计时     NaN    NaN  98.2114
4  1995     1   径向速度   0.472  15.36   4.2308

In [21]:
# 聚合函数和numpy类似，一般是同一个特征的所有数据进行比较。pandas里的聚合函数都是安全用法，可以忽略缺失值
# 如果要想输出所有，直接使用describe()
print(df1.describe()) # 这个打印出来的不好看的原因是：调用对象的字符串表示
df1.describe() # Jupyter 会拿到 describe() 返回的 DataFrame 对象，然后调用 Pandas 专门设计的富文本显示方式

              发现时间      发现数量       行星质量       距地距离       轨道周期
count     5.000000  5.000000   2.000000   2.000000   5.000000
mean   1992.400000  2.200000   6.076000  27.965000  55.626820
std       2.302173  1.095445   7.925253  17.826162  39.670054
min    1989.000000  1.000000   0.472000  15.360000   4.230800
25%    1992.000000  1.000000   3.274000  21.662500  25.262000
50%    1992.000000  3.000000   6.076000  27.965000  66.541900
75%    1994.000000  3.000000   8.878000  34.267500  83.888000
max    1995.000000  3.000000  11.680000  40.570000  98.211400

              发现时间      发现数量       行星质量       距地距离       轨道周期
count     5.000000  5.000000   2.000000   2.000000   5.000000
mean   1992.400000  2.200000   6.076000  27.965000  55.626820
std       2.302173  1.095445   7.925253  17.826162  39.670054
min    1989.000000  1.000000   0.472000  15.360000   4.230800
25%    1992.000000  1.000000   3.274000  21.662500  25.262000
50%    1992.000000  3.000000   6.076000  27.965000  66.541900
75%    1994.000000  3.000000   8.878000  34.267500  83.888000
max    1995.000000  3.000000  11.680000  40.570000  98.211400